Removed unused constructor to fix clang compile error
Compile error was:
In file included from Client/Source/Tuner.cpp:14:
In file included from Client/../third_party/Q/q_lib/include/q/pitch/pitch_detector.hpp:9:
Client/../third_party/Q/q_lib/include/q/fx/moving_average.hpp:50:43: error: cannot convert 'cycfi::duration'
      (aka 'duration<double>') to 'float' without a conversion operator
       : moving_average(std::size_t(sps * float(d)))
                                          ^~~~~~~